major(update): Plone 6.1.2

diff --git a/.github/workflows/test-frontend.yml b/.github/workflows/test-frontend.yml
--- a/.github/workflows/test-frontend.yml
+++ b/.github/workflows/test-frontend.yml
@@ -1,53 +1,90 @@
 name: Frontend CI
 
 on:
-  push:
-    branches: [ "test"]
-    paths:
-      - "frontend/**"
-      - ".github/workflows/test-frontend.yml"
-  workflow_dispatch:
-
-env:
-  IMAGE_NAME_PREFIX: ${{ github.repository }}/frontend
-  IMAGE_NAME_SUFFIX: test
-  NODE_VERSION: 20.x
+  workflow_call:
+    inputs:
+      base-tag:
+        required: true
+        type: string
+      image-name-prefix:
+        required: true
+        type: string
+      image-name-suffix:
+        required: true
+        type: string
+      node-version:
+        required: true
+        type: string
+      volto-version:
+        required: true
+        type: string
 
 defaults:
   run:
     working-directory: ./frontend
 
 jobs:
-#
-#      - name: ESLint
-#        id: eslint
-#        if: ${{ success() || failure() }}
-#        run: yarn run lint:ci
-#
-#      - name: i18n sync
-#        id: i18n
-#        if: ${{ success() || failure() }}
-#        run: make i18n-ci
-#
-#      - name: Unit Tests
-#        id: unit
-#        if: ${{ success() || failure() }}
-#        run: make test
-#
-#      - name: Report
-#        if: ${{ success() || failure() }}
-#        run: |
-#          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
-##          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
-#          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
-##          echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-##          echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-##          echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
-#          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+  code-analysis:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout codebase
+        uses: actions/checkout@v4
 
+      - name: Use Node.js ${{ inputs.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ inputs.node-version }}
+
+      - name: Enable corepack
+        run: |
+          npm i -g corepack@latest
+          corepack enable
+
+      - name: Get pnpm store directory
+        shell: bash
+        run: |
+          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
+
+      - uses: actions/cache@v4
+        name: Setup pnpm cache
+        with:
+          path: ${{ env.STORE_PATH }}
+          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-store-
+
+      - name: Install dependencies
+        run: make install
+
+      - name: Linting
+        id: lint
+        if: ${{ success() || failure() }}
+        run: make lint
+
+      - name: i18n sync
+        id: i18n
+        if: ${{ success() || failure() }}
+        run: make ci-i18n
+
+      - name: Unit Tests
+        id: unit
+        if: ${{ success() || failure() }}
+        run: make test
+
+      - name: Report
+        if: ${{ success() || failure() }}
+        run: |
+          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+          echo '| Lint | ${{ steps.lint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+          echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
+          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
 
   release:
     runs-on: ubuntu-latest
+    needs:
+      - code-analysis
     permissions:
       contents: read
       packages: write
@@ -62,12 +99,15 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: |
-            ghcr.io/${{ github.repository }}/frontend
-          tags: |
-            type=raw,value=test
-            type=raw,value=${{ needs.version.outputs.version }}
+            ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 3000:3000 ghcr.io/${{ github.repository }}/frontend:test
+            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:${{ inputs.base-tag }}
+          flavor:
+            latest=false
+          tags: |
+            type=ref,event=branch
+            type=sha
+            type=raw,value=latest,enable={{is_default_branch}}
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
@@ -88,31 +128,8 @@ jobs:
           platforms: linux/amd64
           context: frontend/
           file: frontend/Dockerfile
-          push: true
+          push: ${{ github.event_name != 'pull_request' }}
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
-            VOLTO_VERSION=18.23.0
-
-
-  deploy:
-    name: Deploy to Remote Server
-    runs-on: ubuntu-latest
-    environment: test  # 👈 Isso seta o ambiente "test"
-    needs: release
-    steps:
-      - name: Connect via SSH and deploy
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          port: 22
-          script: |
-            echo "Fazendo pull da imagem atualizada..."
-            docker pull ghcr.io/cmcuritiba/portal/frontend:test
-
-            echo "Parando e removendo containers com 'frontend' no nome da imagem..."
-            for id in $(docker ps -a | grep frontend | awk '{print $1}'); do
-              docker stop $id || true
-            done
+            VOLTO_VERSION=${{ inputs.volto-version }}
